# Site settings
title: Matthew's Portfolio
description: Tech enthusiast, Anime fan, Matthew Darmadi
baseurl: "" 
url: "http://www.bridyboo.com/" 

# User settings
username: Matthew Brian Darmadi
user_description: I'm a Software Developer graduate from Seattle University winter 2020, currently looking for work opportunity and a sponsor. I have one year of industry experience, and specializes in python, C++/C#.
user_title: Software Developer
email: matthewdarmadi@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
