# Site settings
title: Matthew's Portfolio
description: Tech enthusiast, Anime fan, Matthew Darmadi
<<<<<<< HEAD
baseurl: "" 
url: "http://www.bridyboo.com/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
=======
baseurl: "/website" 
url: "http://www.bridyboo.com" 
>>>>>>> 2f8e0f5f070cd0548cb32f41672753ce52f57a17

# User settings
username: Matthew Brian Darmadi
user_description: I'm a Software Developer graduate from Seattle University winter 2020, currently looking for work opportunity and a sponsor. I have one year of industry experience, and specializes in python, C++/C#.
user_title: Software Developer
email: matthewdarmadi@gmail.com

exclude: ['package.json', 'src' , 'node_modules']

