# Site settings
title: Matthew's Portfolio
description: Tech enthusiast, Anime fan, Matthew Darmadi
baseurl: "" 
url: "https://bridyboo.github.io" 

# User settings
username: Matthew Brian Darmadi
#user_description: I'm a recent Computer Science graduate from Seattle University, currently looking for work opportunity. I have one year of industry experience, and specializes in python, C++, C#, and Java.
user_title: Software Developer
email: matthewdarmadi@gmail.com

exclude: ['package.json', 'src' , 'node_modules']